# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cdn.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcdn.proto\"/\n\x08\x46ileLink\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x02 \x01(\t\"\x18\n\tSignedURL\x12\x0b\n\x03url\x18\x01 \x01(\t2+\n\x03\x43\x44N\x12$\n\x0bGetFileLink\x12\t.FileLink\x1a\n.SignedURLb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cdn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILELINK']._serialized_start=13
  _globals['_FILELINK']._serialized_end=60
  _globals['_SIGNEDURL']._serialized_start=62
  _globals['_SIGNEDURL']._serialized_end=86
  _globals['_CDN']._serialized_start=88
  _globals['_CDN']._serialized_end=131
# @@protoc_insertion_point(module_scope)
