# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Commons.FileService.cdn_pb2 as cdn__pb2


class CDNStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFileLink = channel.unary_unary(
        '/CDN/GetFileLink',
        request_serializer=cdn__pb2.FileLink.SerializeToString,
        response_deserializer=cdn__pb2.SignedURL.FromString,
        )


class CDNServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetFileLink(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CDNServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFileLink': grpc.unary_unary_rpc_method_handler(
          servicer.GetFileLink,
          request_deserializer=cdn__pb2.FileLink.FromString,
          response_serializer=cdn__pb2.SignedURL.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CDN', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
